### PR TITLE
Clarify use of the '$?DISTRIBUTION.ver' (and '.content') methods

### PR DESCRIPTION
**Pull request by tbrowder**
+ Add examples to accompany the descriptions

### CODE REVIEW

**Review by raiph — APPROVED** [review]
I've never clicked an approve in a review before but I presume it's the PR equivalent of a heart and thumbs up emoji in an issue, and better than me just silently reading PRs and thinking "cool", which I do often enough that I'd like to confirm that me doing this is better. (And if instead it's noise, I know to go back to silent nodding of my head.)

**Comment by coke** [comment]
@raiph  - you have a lot of feedback on PRs, this is a perfect way to say you approve of the PR. Helps me to get through them faster and get them merged.

**Comment by coke** [comment]
My one question for @tbrowder : is the `:solo` necessary because of the variable being tested?

**Comment by tbrowder** [comment]
Coke, I think I left it because it was on the original single block of code. I don't pretend to know how that works. I tried to do all the tests you recommend but it always fails with errors from Doc::TypeGraph.

**Comment by coke** [comment]
OK. I'll clean it up in post if needed.

**Pull request merged**
