### PR TITLE
Change the perl6 command line to raku

### PR DESCRIPTION
**Pull request by tinmarino**
Issue #3105 <- See what more todo for renaming process there (1/4 done by this commit)

Only  __command line__ : `perl6` -> `raku`

Found by hand with `ag '(?<!ft=)perl6'`

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Isn't it a bit too early?

**Comment by tinmarino** [comment]
> Isn't it a bit too early?

Yes it is, compared to some others. But if everybody says that ...
@bduggan did a full rename in [p6-jupyter-kernel](https://github.com/bduggan/p6-jupyter-kernel/commit/36ca275216f85d9f6e054a7e6adae660030d5b09) -> I had to get my version up to date, so I change others lol.

**Comment by tinmarino** [comment]
The only requirement here is to get `raku` executable.
I don't know who is also changing the urls: `github.com/Raku` and `https://docs.raku.org/`
Nice issues for a newcomer : getting me to the the file tree

**Comment by AlexDaniel** [comment]
@tinmarino URLs is one thing, but changing the executable name in the docs assumes that users already can type `raku` in their terminal and get something running. Most distros probably don't provide `raku` executable yet, so it's a bit too early I think.

**Comment by JJ** [comment]
El dom., 22 mar. 2020 a las 17:40, Aleks-Daniel Jakimenko-Aleksejev (<
notifications@github.com>) escribió:

> @tinmarino <https://github.com/tinmarino> URLs is one thing, but changing
> the executable name in the docs assumes that users already can type raku
> in their terminal and get something running. Most distros probably don't
> provide raku executable yet, so it's a bit too early I think.
>

That, too. perl6 works all over, and it's not even deprecated. raku might
not.

**Comment by tinmarino** [comment]
@AlexDaniel, I did not think about end users, which are actually the clients of the doc ... you are right: some years are needed for Debian repo to be up to date (not in Raku's scope).

@JJ I did it by hand but then I could separate PR for each file type, at least directory ...

@Both, should I close (I'll keep a branch in my local for the changes not to be garbage collected) ?

**Comment by tinmarino** [comment]
@JJ : I make a separate for `Perl5 -> Perl` (issue #3091 -> commit 8da4c685de3c)

**Comment by JJ** [comment]
@tinmarino sorry, you lost me here. Are you saying that you are going to make a separate one for that? Or that you have done it already?

**Comment by tinmarino** [comment]
@JJ : I did not do more already. Asking if I should work.

This PR has 2 enormous commits.
1. Perl6 -> Raku) is too early
2. Perl5 -> Perl too big.

I am asking if I should divide 2 in let's say 10 commits and make another PR ?

PS : I was not clear at all (my bad)

**Comment by JJ** [comment]
Right. Do it little by little, not more than 5 files at a time.

**Pull request closed without merging**
