### PR TITLE
Revert "Add ≡ (equivalent to ==) and ≢ (equivalent to !=)"

### PR DESCRIPTION
**Pull request by JJ**
Reverts Raku/doc#3674

### CODE REVIEW

**Comment by AlexDaniel** [comment]
3 reverts for what? Yes, the op is wrong, but it could've been fixed with just one commit.

**Comment by JJ** [comment]
Well, I use rebase instead of squash usually. No big deal.

**Comment by AlexDaniel** [comment]
@lizmat you're on a mission to downvote all my comments, or what?

**Comment by AlexDaniel** [comment]
So, to clarify, a relatively new contributor submitted a PR that you reviewed poorly. Then, once it was pointed out that there's a little mistake and it talks about a different operator, you reverted the whole thing with three revert commits, instead of just adding missing parens. Not only it unnecessarily clutters the git history, but it also makes it somewhat hard for new contributors to proceed. Why revert it in the first place? You sure that the revert sends the right message?

But, as it seems, this is considered normal around here, and it's not the first time I see this attitude. The downvotes that completely fail to understand the issue, and are there just because I pointed it out, are also very telling.

**Pull request merged**
