### PR TITLE
Add utility to test doc-website templates

### PR DESCRIPTION
**Pull request by coke**
## The problem

templates in doc-website exist but are not verified to pass raku/doc's basic pod structure.

## Solution provided

util/test-website

### CODE REVIEW

**Comment by coke** [comment]
If we keep the tests in raku/doc and the templates in doc-website, what's the advantage of running the tests from either area? Either way we have to cover the other repo, yes?

**Comment by cfa** [comment]
Just that this requires cloning the other repo in order to run tests on its content.

**Comment by coke** [comment]
And in the other case, we clone this repo to get the tests to run.

**Comment by coke** [comment]
So, since either way we have to do a clone to get the tests and the files in the same place, let's go with this one for now.

**Comment by finanalyst** [comment]
see https://github.com/Raku/doc-website/issues/103

**Pull request merged**
