### PR TITLE
update information about methods for distributing modules

### PR DESCRIPTION
**Pull request by sdondley**
## The problem

information about how to distribute modules is out of date

## Solution provided

updates info about how to distribute a module

### CODE REVIEW

**Comment by coke** [comment]
Please verify this passes:

```
TEST_FILES=doc/Language/modules.pod6 make xtest
```

(I tried do this the hard way and saw a whitespace failure)

**Comment by sdondley** [comment]
Passed for me:

```
> $ TEST_FILES=doc/Language/modules.pod6 make xtest                                                                                                     [±master ✓]
if [ "" != "" ]; then prove -j  -e raku t xt; else prove -e raku t xt; fi
t/00-meta.t ................ ok
t/02-pod-valid.t ........... ok
t/03-tests-valid.t ......... skipped: No test files specified
t/04-pod6.t ................ ok
t/05-tabs.t ................ ok
xt/aspell.t ................ ok
xt/braces.t ................ ok
xt/camelia-invocations.t ... ok
xt/check-signatures.t ...... skipped: To run check-signatures, please specify the path to the Rakudo git checkout with the RAKUDO_SRC environment variable
xt/double-dots.t ........... ok
xt/duplicates.t ............ ok
xt/examples-compilation.t .. ok
xt/final-newline.t ......... ok
xt/headings.t .............. ok
xt/lib-test-files.t ........ ok
xt/links-not-links.t ....... ok
xt/perl-nbsp.t ............. ok
xt/return-type.t ........... ok
xt/routine-definitions.t ... ok
xt/space-after-comma.t ..... ok
xt/trailing-whitespace.t ... ok
xt/type-graph.t ............ ok
xt/word-variants.t ......... ok
xt/words.t ................. ok
All tests successful.
```

**Comment by tbrowder** [comment]
I would like to see the Zef repo as first mentioned as well as stating it should be the only one used for new modules. I would only mention the others in the past tense with no details about how to use them.

**Comment by sdondley** [comment]
@tbrowder being new, I don't have an informed opinion on your suggestions regarding cpan and p6c.

**Pull request closed without merging**
