### PR TITLE
Pkg interp: complete example, improve var names

### PR DESCRIPTION
**Pull request by tbrowder**

### CODE REVIEW

**Comment by JJ** [comment]
it seems to be in conflict with one of your previous PRs?

**Comment by tbrowder** [comment]
I just resolved it. I didn't think you would merge my first attempt so fast!  :-D

**Comment by tbrowder** [comment]
How are you, JJ? I miss you on IRC!

**Review by JJ — APPROVED** [review]
Looks great. Thanks!

**Comment by JJ** [comment]
There's still a conflict in a few lines, I'd be hard pressed to solve it. Can you please check?

**Comment by tbrowder** [comment]
On Tue, Sep 7, 2021 at 10:40 Juan Julián Merelo Guervós <
***@***.***> wrote:

> There's still a conflict in a few lines, I'd be hard pressed to solve it.
> Can you please check?
>
I think I fixed it.

**Comment by JJ** [comment]
Great. Thanks!

**Pull request merged**
