### PR TITLE
Call it "Pod", not "POD" or "Pod6"

### PR DESCRIPTION
**Pull request by softmoth**
It's not Plain Ol' Documentation in Raku. It's just Pod. From S26:

> Pod is an evolution of Perl 5's Plain Ol' Documentation (POD) markup.

## The problem

_POD_ and _Pod6_ are Perlisms that don't really fit after the name change to Raku.

## Solution provided

Following [S26](https://design.raku.org/S26.html), call Raku's documentation _Pod_, and leave _POD_ to Perl. Remove as many references to `Pod6` and `POD` as possible.

**TODO**
- Rename all docs files to `*.rakudoc` instead of `*.pod6`
- Rename `:lang<pod6>` in code blocks

### CODE REVIEW

**Comment by JJ** [comment]
OK, several problems here.
1. We really don't like PRs with more than 4-5 files, every one with a few changes. 22 files takes a long time to review, and the whole PR might be stuck because of a single comma.
2. See #1948. That change was already made, in the other direction. In general, it's better to achieve a consensus on a big change before committing to it. It was called pod6, which is simply an abbreviation for Perl 6 Pod. 
3. If we are going to make some change now, it will be to rakudoc, probably, not pod. 
4. Changing all file names to rakudoc is in the roadmap, but not something that we will do inmediately.

Thanks anyway for the work, but I would really prefer that you keep it small and to any other grammar fixes or any other kind that you might have bump into when doing it.

**Comment by softmoth** [comment]
It's a proposal. I didn't spend much time on it. If people hate it, it can be canned. I think discussing things can be more efficient when there's already a diff to talk about.

Using "Rakudoc" instead of "Pod" is OK by me. Using "Pod 6" is not, I think, appropriate.

**Comment by JJ** [comment]
> It's a proposal. I didn't spend much time on it. If people hate it, it can be canned. I think discussing things can be more efficient when there's already a diff to talk about.
> 

Yep, but that change goes in a particular direction, so instead of arriving to a consensus of what to do, it's a binary decision: take it or leave it.

> Using "Rakudoc" instead of "Pod" is OK by me. Using "Pod 6" is not, I think, appropriate.

Nor we are using it. It's pod6, short for Perl 6 Pod. Rakudoc, in the medium term, is probably the way to go.

**Comment by tbrowder** [comment]
I'm working on a couple of modules that involve using pod as a markup language to produce PDF output. What should I call **pod**?

The first module I have named **Pod::To::PDF** and a follow-on to be called **DocWriter**, so I do need some guidance, *por favor, senor*.

**Comment by JJ** [comment]
Pod::to is the admitted way of calling those modules, so no problem there. In the documentation, we generally call it pod6, the same as the extensions.

**Comment by tbrowder** [comment]
Thank. BTW, I just read fully @finanalyst's 20th Advent article and saw he wrote of what I was thinking but so much better and more thoroughly. The literate programming aspect of pod is what I had a eureka moment over a while back, and his references were greatly appreciated.

**Comment by softmoth** [comment]
I think this issue is more confusing than helpful, so I'll close it. Thanks for the discussion and review.

**Pull request closed without merging**
