### PR TITLE
Add example of file path analysis

### PR DESCRIPTION
**Pull request by tbrowder**
## The problem

No existing practical example of file path analysis.

## Solution provided

An example is added.

### CODE REVIEW

**Comment by Altai-man** [comment]
Maybe add getting extension and a filename without extension too?

**Comment by tbrowder** [comment]
> Maybe add getting extension and a filename without extension too?

Actually I only know how to do that crudely with a regex. Is there a method I haven't known about?

**Comment by Altai-man** [comment]
I'm not aware about the "filename without extension", so here is this:

```
my $file-name = "financial.data";
# Convert the string into an IO::Path object
my $path = $file-name.IO;
say $path.absolute;                                 # OUTPUT: «/usr/local/data/financial.data␤»
# Stringify the path's parts:
say $path.dirname;                                  # OUTPUT: «/usr/local/data␤»
say $path.basename;                                 # OUTPUT: «financial.data␤»
say $path.extension;                                # OUTPUT: «data␤»
my $extension-chars = $path.extension.chars + 1;
say $path.basename.substr(0, * - $extension-chars); # OUTPUT: «financial␤»
```

**Comment by tbrowder** [comment]
How about this
    my @pieces = $basename.split: /‘.’/;
    my $suff = @pieces.pop;
    my $stem = @pieces.join(‘.’);

**Comment by coke** [comment]
https://docs.raku.org/type/IO::Path#method_extension

**Comment by tbrowder** [comment]
Good, when I first looked at it, it wasn’t obvious to me how to get the name with the extension removed.

Thanks, I’ll try it.

**Comment by Altai-man** [comment]
>my @pieces = $basename.split: /‘.’/;

My personal grudge with regexes is it's generally advised to avoid them unless you absolutely cannot, for performance reasons, so .substr is far cheaper than a regex.

We can merge the PR with the suggested code, I think, it's a nice addition overall.

**Review by Altai-man — APPROVED** [review]

**Pull request merged**
