### PR TITLE
minor fix: code quote within code quote

### PR DESCRIPTION
**Pull request by kybr**
## The problem

<...> was code quoted twice

## Solution provided

removed the in-line quoting

### CODE REVIEW

**Comment by coke** [comment]
The C<> here is intended to show the text

```
<...>
```

as code, which it's doing. the brackets are part of the text to display, corresponding to the ```qw``` in the Perl 5 code.

**Comment by coke** [comment]
I would recommend changing "rendered" here, actually, because I think that is a source of confusion. "written as" is probably a better choice.

**Comment by kybr** [comment]
Ok. Perhaps I am wrong. But this is what I see on the [Perl to Raku guide - functions](https://docs.raku.org/language/5to6-perlfunc#quoting):

```
q/.../;  # is still equivalent to using single quotes. 
qq/.../; # is still equivalent to using double quotes. 
qw/.../; # is more commonly rendered as C<< <...> >> in Raku. 
```

Is the reader supposed to see the `C<< >>` part? I don't think so. Because the whole block above is itself is under a `=for code :lang<perl>` thing, I think the `C<< <...> >>` renders literally. I checked on `#raku` to see if anyone else thought it might be a mistake and [at least one person thought it was](https://colabti.org/irclogger/irclogger_log/raku?date=2021-05-18#l321).

**Comment by coke** [comment]
Ah, I assumed the pod was rendering and did not verify. Good catch, in that case you’re 100% right!

**Comment by kybr** [comment]
Cool! And, "written as" is better. I'll amend the PR when I get back to a computer.

**Review by JJ — APPROVED** [review]
Thanks!

**Pull request merged**
