### PR TITLE
Add glossary to HomePage.pod6

### PR DESCRIPTION
**Pull request by 0rir**
Link from HomePage to glossary.

### CODE REVIEW

**Comment by coke** [comment]
Why is the one change showing a merge commit?

**Comment by coke** [comment]
you should rebase in that case, not merge.

**Comment by 0rir** [comment]
Sorry, @coke,  I am not sure how I grabbed 2 commits.
Without advice, my best way to fix this is to close this, correct my unpublished 'space' and re-PR.  Okay?

**Comment by coke** [comment]
you can force push on your branch if needed, or drop this PR and create a new one with just the desired commit, either way is fine.

**Pull request closed without merging**
