### PR TITLE
Opener chars doc unicode mismatch fix

### PR DESCRIPTION
**Pull request by mykhal**
This should solve [Opener graphemes documentation unicode mismatch #3917](https://github.com/Raku/doc/issues/3917)

### CODE REVIEW

**Comment by mykhal** [comment]
Oh, for that singular change, it contains more commits than I wanted..

**Comment by Altai-man** [comment]
This probably should be an addition rather than a replacement which can break someone's code.

**Comment by mykhal** [comment]
@Altai-man sorry, still getting into github UI, but I did update my fork, and made new branch for that...

**Comment by mykhal** [comment]
@Altai-man but you likely mean the change itself. I get it now.

**Comment by mykhal** [comment]
@Altai-man  .. in fact, i would not say it's exactly "replaced", the original table "encouraged" use of character/codepoint, which is immediately normalized, see related closed rakudo issue linkd in this raku issue.

**Comment by mykhal** [comment]
Well, I agree that this singular fix might not be the best way of updating the file, I'm unable to check if there are more characters to mention, and not sure whether every possible equivalent Unicode character variants should be listed.

**Comment by JJ** [comment]
Agreeing with @Altai-man; it's out of order, too, since they seem to be sorted. Plus there's a conflict now?

**Comment by tbrowder** [comment]
I created that original page from a Raku script. It should be around somewhere if someone wants to use it.

**Comment by tbrowder** [comment]
Before any merge I would like someone to see if there is an error in how I created the table. I will try to do that myself soon but right now I am slammed with contractor visits and getting my house ready to be sold.

If the table does need to be changed I agree with @Altai-man's cautionary comment.

**Comment by coke** [comment]
The utility for this should exist in util/ or at least be documented in writing-docs.

**Comment by tbrowder** [comment]
Recommend this be closed since PR #4207 will remove the subject table.

**Comment by coke** [comment]
Closing per @tbrowder

**Pull request closed without merging**
