### PR TITLE
Remove unused Pod::Convenience method

### PR DESCRIPTION
**Pull request by coke**
Removed these methods (and their tests), ran ```make xtest``` - no failures. No references to this method elsewhere in the repo; able to do a documentable build. Not all the methods had tests that were removed, but all the tests were for removed methods, so the test file is gone.

### CODE REVIEW

**Comment by coke** [comment]
While switching away from this lib entirely has been slow going, removing this function is an easy way to reduce the footprint.

**Comment by coke** [comment]
update coming that will remove more methods...

**Review by JJ — APPROVED** [review]
Probably safe if we remove the whole module too...

**Comment by JJ** [comment]
Thanks!

**Pull request merged**
