### PR TITLE
Add a reference to Whitespace

### PR DESCRIPTION
**Pull request by tbrowder**
+ Grammar tweaks
+ Add more examples
+ Align examples of Unicode naming corrections for clarity
  - Use comments to distinguish correct versus incorrect naming versions

### CODE REVIEW

**Review by coke — APPROVED** [review]

**Comment by coke** [comment]
Thanks - note the ```X<...>``` needed to be ```X<|...>``` which I had forgotten since the last time I looked at xt/search-categories.

**Comment by tbrowder** [comment]
I forgot about the proper format. I did look at another example and thought I had copied it correctly, but, alas. I'll check the docs again. Maybe that's why "make test was failing!"

**Comment by tbrowder** [comment]
Coke, I did look at the docs before I used the reference link, but I failed to finish it as I intended. My initial motivation for the PR was because an existing search for "whitespace" turned up very little, and nothing about that section. I searched all the source docs and found no reference links. 

What I think that line needs to look like is more like this (as I keep forgetting, the part before the vertical bar is not case-sensitive, but the part following it is):

    =head1 X<whitespace|Language, whitespace> Whitespace...

**Comment by coke** [comment]
OK - this one is merged, feel free to change it directly if you have a small update.

**Pull request merged**
